"""Build the self-contained Overleaf bundle from paper/main.tex.

Overleaf projects have no ../tables/, so the authored source cannot be
uploaded directly: it fails with "File `../tables/main_results_v2.tex' not
found" and emits no PDF. This inlines that input and writes the pair of files
the project actually needs.

Run after editing paper/main.tex, and upload the output -- never the source.

Usage:
    python scripts/build_overleaf_bundle.py
"""
import io
import os
import re
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(_REPO, "paper")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(_REPO, "paper", "overleaf_upload")
os.makedirs(OUT, exist_ok=True)

main = io.open(os.path.join(SRC, "main.tex"), encoding="utf-8").read()

INPUT = re.compile(r"^([ \t]*)\\input\{([^}]+)\}[ \t]*$", re.M)


def resolve(match):
    indent, target = match.group(1), match.group(2)
    for cand in (
        os.path.join(SRC, target + ".tex"),
        os.path.join(SRC, target),
        os.path.normpath(os.path.join(SRC, target + ".tex")),
    ):
        if os.path.exists(cand):
            body = io.open(cand, encoding="utf-8").read().rstrip("\n")
            name = os.path.basename(cand)
            return (f"{indent}% ---- begin {name} "
                    f"(inlined; edit here, this is the single source) ----\n"
                    f"{body}\n"
                    f"{indent}% ---- end {name} ----")
    raise SystemExit(f"could not resolve \\input{{{target}}}")


# Two passes: sections may themselves \input the generated table.
flat = main
for _ in range(3):
    new = INPUT.sub(resolve, flat)
    if new == flat:
        break
    flat = new

# Check only uncommented lines. main.tex documents the camera-ready build
# command in a comment, and that comment legitimately contains an input
# directive that must not be resolved.
_live = "\n".join(l for l in flat.split("\n") if not l.lstrip().startswith("%"))
_left = re.findall(r"\\input\{([^}]+)\}", _live)
if _left:
    raise SystemExit("unresolved input remains: " + ", ".join(_left))

header = (
    "% =====================================================================\n"
    "% JudgeSense - single-file build for Overleaf.\n"
    "%\n"
    "% Generated by flattening paper/main.tex and its \\input files. The\n"
    "% section boundaries are marked below; this file is now the source of\n"
    "% truth for Overleaf, so edit it here.\n"
    "%\n"
    "% ANONYMITY: \\blindtrue below produces the anonymous review copy.\n"
    "% Comment that line out for the camera-ready. Do not upload a named PDF\n"
    "% for review - TMLR review copies are anonymous.\n"
    "%\n"
    "% The results table is inlined from tables/main_results_v2.tex, which is\n"
    "% GENERATED by scripts/regenerate_results.py from committed raw outputs.\n"
    "% If the numbers change, regenerate there and re-flatten; do not hand-edit\n"
    "% the table, or the paper and the data will drift apart.\n"
    "% =====================================================================\n"
)

io.open(os.path.join(OUT, "main.tex"), "w", encoding="utf-8", newline="\n").write(header + flat)

bib = io.open(os.path.join(SRC, "references.bib"), encoding="utf-8").read()
io.open(os.path.join(OUT, "references.bib"), "w", encoding="utf-8", newline="\n").write(bib)

print(f"  main.tex       {len(header + flat):>7} bytes")
print(f"  references.bib {len(bib):>7} bytes")
print(f"  inputs resolved: {len(INPUT.findall(main))} top-level")
